version: "3.3"

services:
  jenkins:
    image: my-custom-jenkins
    container_name: jenkins-server
    privileged: true
    hostname: jenkinsserver
    user: root
    labels:
      com.cloudberry.description: "Jenkins-Server for Final Project / Adaptive Lean Software Testing"
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      jenkins-net:
        aliases:
          - jenkins-net
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  smee:
    image: my-smee-client
    command: smee -u https://smee.io/1rgXJjMLMQL67pj -t http://jenkins:8080/jenkins/github-webhook/
    depends_on:
      - jenkins
    networks:
      jenkins-net:
        aliases:
          - jenkins-net

networks:
  jenkins-net: