server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
      - id: payments-aggregate
        uri: http://payments-processor-app:8081/
        predicates:
        - Path=/payments/aggregator
        filters:
        - MaskSensitiveResponse=loanNumber,%%%
      - id: customers-aggregate
        uri: http://customers-processor-app:8082/
        predicates:
        - Path=/customers/aggregator
        filters:
        - MaskSensitiveResponse=loanNumber,%%%